imports:
    - { resource: parameters.yml }

services:
    nomismomis.clashpoints.controller:
        class: nomismomis\clashpoints\controller\main
        arguments:
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@user'

    nomismomis.clashpoints.service:
        class: nomismomis\clashpoints\service
        arguments:
            - '@user'
            - '%nomismomis.clashpoints.tables.demo_table%'

    nomismomis.clashpoints.listener:
        class: nomismomis\clashpoints\event\main_listener
        arguments:
            - '@controller.helper'
            - '@template'
            - '@user'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }

    nomismomis.clashpoints.notification.type.demo:
        class: nomismomis\clashpoints\notification\type\demo
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - '@user_loader'
            - '@dbal.conn'
            - '@cache.driver'
            - '@user'
            - '@auth'
            - '@config'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%tables.notification_types%'
            - '%tables.notifications%'
            - '%tables.user_notifications%'
        calls:
            - [set_controller_helper, ['@controller.helper']]
        tags:
            - { name: notification.type }
